### ISSUE TITLE
Use same style sheet document.

### ISSUE THREAD

**Issue by pidster** [microservices-demo/microservices-demo.github.io#12]
We're currently using two style sheets:

1. https://github.com/microservices-demo/microservices-demo/tree/master/docs/assets/css
2. https://github.com/microservices-demo/microservices-demo.github.io/tree/master/assets/css

We should just use a single style sheet (probably in the web repo).

**Comment by nustiueudinastea** [comment]
Fixed by https://github.com/microservices-demo/microservices-demo/pull/465
