### ISSUE TITLE
Can you clarify how to use local build of docs?

### ISSUE THREAD

**Issue by rberlind** [microservices-demo/microservices-demo.github.io#54]
Could you guys clarify how to use the local build of the docs?  I know that I can run  docker-compose -f docker-compose.yml up -d to launch the containers and that I can access the home page at http://localhost:4000.  But the links to the deployment pages seem broken since they point to things like http://localhost:4000/microservices-demo/deployment/docker-compose.html which is actually available at http://localhost:4000/deployment/docker-compose.html.

I presume that I am supposed to edit _config.yml.dev, or possibly rename it temporarily to _config.yml while renaming _config.yml to _config.yml.prod. 

Could someone clarify that?

Thanks

**Comment by etiennetremel** [comment]
Hi @rberlind, there is in fact some issue with the build system. I don't really understand the reason of having a **config.yml.dev**.
Hopefully this PR could help you getting started: https://github.com/microservices-demo/microservices-demo.github.io/pull/75.

**Comment by rberlind** [comment]
Thanks.  I don't need to do this anymore since I switched jobs.
