### ISSUE TITLE
it's a "sock shop", not a "socks shop"

### ISSUE THREAD

**Issue by rade** [microservices-demo/microservices-demo.github.io#57]
Some incorrect pluralisation has crept into the [docs](https://microservices-demo.github.io/): various places, including the title, refer to a thing called the "Socks Shop" instead of "Sock Shop".

**Comment by rberlind** [comment]
I'm somewhat new to the microservices-demo project and did use "Socks Shop" at the top of the new Apcera deployment page.   But I would note that "Socks Shop is used exclusively 7 times on the home page and also on the Introduction page and the User Accounts page.  So, it shouldn't be too surprising if new people like myself end up thinking of the app as "Socks Shop".  I agree that harmonizing usage to one or the other would be better.

**Comment by rade** [comment]
>  I agree that harmonizing usage to one or the other would be better.

We should harmonize to the *correct* spelling, which is "Sock Shop". From https://www.englishclub.com/grammar/nouns-compound.htm
> Note that with compound nouns made of [noun + noun] the first noun is like an adjective and therefore does not usually take an -s. A tree that has apples has many apples, but we say an apple tree, not apples tree; matchbox not matchesbox; toothbrush not teethbrush.

**Comment by rberlind** [comment]
That certainly makes sense grammatically.  And searching online for actual stores that sell other products, I do find (even here in the U.S.) that most stores do use singular for the first word.  So, I see "Shoe Store", "Ski Shop", and "Ski Haus".  I'll change my new page to comply.  I'll leave it to others to make any other changes.

On a different topic, do you have any idea how to fix the broken link for the apcera.html deployment page?  I looked through the history of the doc_menu.html page, and it seems that it used to use {{site.deploy_doc_url_prefix}} to get the links corect, but that was removed.

What I find very odd is that the deployment files are under the deployment directory, but based on the URLs in doc_menu.html, it seems they should actually all be under microservices-demo/deployment.  Does an administrator have to adjust something for the apcera page to be deployed to the correct location?  Note that it does exist at https://microservices-demo.github.io/deployment/apcera.html.

Another problem is that the Apcera links which show up on the main pages do not show up on the individual deployment pages.

**Comment by rade** [comment]
@rberlind please file a separate issue for your broken link problem.

**Comment by rberlind** [comment]
I already had done that yesterday: https://github.com/microservices-demo/microservices-demo.github.io/issues/56

**Comment by jasonrichardsmith** [comment]
This was updated in #59

**Comment by rade** [comment]
Thank you!
